import type { Metadata } from 'next';
import './globals.scss';
import React, { ReactElement } from 'react';
import Header from './components/Header/Header';
import styles from './layout.module.scss';
import ReduxProvider from '../providers/ReduxProvider';
import UserLoader from './components/UserLoader/UserLoader';
import { PrimeReactProvider } from 'primereact/api';
import 'primereact/resources/themes/saga-blue/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css';
import { MessageProvider } from '../providers/MessageProvider';
import FooterWrapper from './components/FooterWrapper/FooterWrapper';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): ReactElement {
  return (
    <html lang="uk">
      <body className={styles.body}>
        <ReduxProvider>
          <PrimeReactProvider>
            <MessageProvider>
              <UserLoader />
              <Header />
              <div className={styles.body__container}>
                <div className={styles.body__inner}>{children}</div>
              </div>
              <FooterWrapper />
            </MessageProvider>
          </PrimeReactProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
